### ISSUE TITLE
ember - address jquery deprecation

### ISSUE THREAD

**Issue by kaden-weber** [ManhanGroup/massbuilds#7]
`DEPRECATION: The integration of jQuery into Ember has been deprecated and will be removed with Ember 4.0. You can either opt-out of using jQuery, or install the `@ember/jquery` addon to provide the jQuery integration. Please consult the deprecation guide for further details: https://emberjs.com/deprecations/v3.x#toc_jquery-apis`

It looks like jQuery is used in an involved way in the project, evaluate if it would be reasonable to remove it entirely. If not, follow the deprecation guide to use jQuery correctly. 

Best practice might be to move on from jQuery as it is losing popularity, but getting on to the right version of it would be acceptable.

**Comment by PRO-BROS** [comment]
Very well. Facing the same issue but now resolved on my [site](https://prhocoding.com/)
